language: node_js
node_js:
  - "10"

sudo: false

branches:
  only: master

after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
